# Generated by Django 4.2.7 on 2024-01-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='catagory',
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
    ]
