# Generated by Django 4.2.7 on 2024-01-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='catagory',
            new_name='category',
        ),
    ]
