# Generated by Django 4.2.7 on 2024-02-15 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connecttoexpert',
            old_name='expet',
            new_name='expert',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expert.expert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert',
            name='url_to_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expert.expert'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
