# Generated by Django 4.2.7 on 2024-02-16 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0002_rename_expet_connecttoexpert_expert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestedExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.expert')),
            ],
        ),
    ]
