# Generated by Django 4.2.7 on 2024-02-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_userinterestedexperts_experttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterestedexperts',
            name='expert',
        ),
        migrations.AddField(
            model_name='userinterestedexperts',
            name='expertTag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expert.experttag'),
            preserve_default=False,
        ),
    ]
