# Generated by Django 4.2.7 on 2024-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_expertlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='blue_check',
            field=models.CharField(default='false', max_length=15),
        ),
    ]
