# Generated by Django 4.2.7 on 2024-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signInDate',
            field=models.DateField(default='2023-10-10'),
        ),
    ]
