# Generated by Django 4.2.7 on 2024-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_signindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=505.5, unique=True),
            preserve_default=False,
        ),
    ]
