# Generated by Django 4.2.7 on 2024-01-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by_uaer',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url_to_image',
            new_name='url_to_media',
        ),
    ]
