# Generated by Django 4.2.7 on 2024-02-19 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0010_businessfollower'),
        ('post', '0002_rename_created_by_uaer_post_created_by_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('url_to_media', models.CharField(blank=True, max_length=255, null=True)),
                ('video_or_image', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('url_to_media', models.CharField(blank=True, max_length=255, null=True)),
                ('video_or_image', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
