# Generated by Django 4.2.7 on 2024-01-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_video_or_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catagory',
            field=models.CharField(default=2002, max_length=255),
            preserve_default=False,
        ),
    ]
