# Generated by Django 4.2.7 on 2024-01-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('article', '0003_article_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='catagory',
            field=models.CharField(default='all', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date_time',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='related_to_business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_to_media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
