# Generated by Django 4.2.7 on 2023-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(default='all', max_length=255)),
                ('private', models.IntegerField()),
                ('time', models.TimeField()),
                ('url', models.CharField(max_length=255)),
                ('urlToImage', models.CharField(max_length=255)),
            ],
        ),
    ]
