# Generated by Django 4.2.7 on 2024-01-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_storytypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story.storytypes'),
            preserve_default=False,
        ),
    ]
