# Generated by Django 4.2.7 on 2024-01-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_valuation', models.CharField(blank=True, max_length=255, null=True)),
                ('total_assets_value', models.CharField(blank=True, max_length=255, null=True)),
                ('total_investment', models.CharField(blank=True, max_length=255, null=True)),
                ('working_capital', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_facilities', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_of_return', models.CharField(blank=True, max_length=255, null=True)),
                ('debt_to_capital_ratio', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_value_added', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_of_company_valuation', models.CharField(blank=True, max_length=255, null=True)),
                ('comparison_of_number_of_employees', models.CharField(blank=True, max_length=255, null=True)),
                ('comparison_of_annual_profit', models.CharField(blank=True, max_length=255, null=True)),
                ('comparison_of_profit_after_taxes', models.CharField(blank=True, max_length=255, null=True)),
                ('comparison_of_working_capital', models.CharField(blank=True, max_length=255, null=True)),
                ('coparison_of_gross_value_added', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gtowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_of_company_valuation', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_of_total_investment', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_of_working_capital', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_of_annual_profit', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_of_monthly_profit', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_of_after_taxes_profit', models.CharField(blank=True, max_length=255, null=True)),
                ('growth_of_gross_value_added', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_employees', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Growth',
        ),
        migrations.AddField(
            model_name='income',
            name='allocatable_profit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='annual_costs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='annual_income',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='annual_profit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='monthly_costs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='monthly_income',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='monthly_profit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='profit_after_taxes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
