# Generated by Django 4.2.7 on 2024-01-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_capital_comparison_gtowth_staff_delete_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='for_business',
            field=models.ForeignKey(default=2002, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparison',
            name='for_business',
            field=models.ForeignKey(default=2002, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtowth',
            name='for_business',
            field=models.ForeignKey(default=2002, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='for_business',
            field=models.ForeignKey(default=2002, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='for_business',
            field=models.ForeignKey(default=2002, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='blue_check',
            field=models.CharField(default='False', max_length=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='url_to_business_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
