# Generated by Django 4.2.7 on 2024-01-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_capital_for_business_comparison_for_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='catagory',
            field=models.CharField(default=2002, max_length=255),
            preserve_default=False,
        ),
    ]
