# Generated by Django 4.2.7 on 2024-01-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gtowth',
            new_name='Growth',
        ),
    ]
