# Generated by Django 4.2.7 on 2024-01-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_rename_gtowth_growth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
