# Generated by Django 4.2.7 on 2024-02-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_businesstag_businesslike_businesscomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscomment',
            old_name='text',
            new_name='comment',
        ),
    ]
