# Generated by Django 4.2.7 on 2024-02-14 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0008_rename_text_businesscomment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBusinessInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businesstag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
