# Generated by Django 4.2.7 on 2024-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_connecttobusiness_businessstaff_businesspartnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
