# Generated by Django 4.2.7 on 2024-02-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_businessstaff_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
