# Generated by Django 4.2.7 on 2024-02-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_businessstaff_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartnership',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
